[libdefaults]
    default_realm = IT.KMITL.AC.TH
    dns_lookup_realm = true
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false

[realms]
    IT.KMITL.AC.TH = {
        kdc = IT.KMITL.AC.TH
        admin_server = IT.KMITL.AC.TH
        default_domain = IT.KMITL.AC.TH
    }

[domain_realm]
    .it.kmitl.ac.th = IT.KMITL.AC.TH
    it.kmitl.ac.th = IT.KMITL.AC.TH

[logging]
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmin.log
    default = FILE:/var/log/krb5lib.log
