services:

  samba:
    build:
      context: ./samba
      dockerfile: Dockerfile
    container_name: samba-server
    hostname: SMB-67070109
    network_mode: host
    dns:
      - 161.246.38.141
      - 10.70.37.141
    volumes:
      - ./samba/smb.conf.template:/smb.conf.template:ro
      - ./samba/krb5.conf:/etc/krb5.conf:ro
      - ./samba/shares.conf:/etc/samba/shares.conf
      - samba-data:/var/lib/samba
      - ./data/shared:/mnt/shared
    environment:
      - WORKGROUP=IT
    healthcheck:
      test: ["CMD-SHELL", "pidof smbd > /dev/null && echo ok || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: smb-webapp
    networks:
      - smb-network
    ports:
      - "8080:8080"
    volumes:
      - samba-data:/var/lib/samba
      - ./samba/shares.conf:/etc/samba/shares.conf
      - ./data/shared:/mnt/shared
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - SAMBA_CONTAINER=samba-server
      - SAMBA_DATA_PATH=/var/lib/samba
      - API_HOST=0.0.0.0
      - API_PORT=8080
    depends_on:
      samba:
        condition: service_healthy
    restart: unless-stopped


networks:
  smb-network:
    driver: bridge

volumes:
  samba-data:
